#
# Local site settings
theme-name: GCWeb
title: "GCWeb, the Canada.ca official theme" # Site name or title
website: "https://wet-boew.github.io/gcweb/" # URL of your public facing website
site:
  lang: fr

#
# Page front matter defaults
defaults:
  - scope:
      path: "" # Ensure it's applied to all pages
    values:
      layout: default

#
# Jekyll settings
timezone: America/Toronto # Timezone for blog posts and alike
#verbose: true
#quiet: false
sass:
  sass_dir: "sites"
#  load_paths: [
#    "node_modules" # we might only need bootstrap scss
#  ,
#    "node_modules/wet-boew/node_modules" # todo: find a way to include it.
#  ]

#
# Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE*
- SECURITY.md
- Gruntfile.coffee
- CNAME
- "*.tmp"
- Gemfile
- Gemfile.lock
- gcweb-jekyll.gemspec
- .jekyll-cache
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
