name: CD

on:
  push:

jobs:
  deploy-jekyll:

    runs-on: ubuntu-latest

    environment: continuous_deploy

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

#      - name: Cache node modules
#        uses: actions/cache@v2
#        if: ${{ !env.ACT }}
#        env:
#          cache-name: cache-node-modules
#        with:
#          # npm cache files are stored in '~/.npm' on Linux/macOS
#          path: ~/.npm
#          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-build-${{ env.cache-name }}-
#            ${{ runner.os }}-build-
#            ${{ runner.os }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm i -g bower grunt-cli
          npm ci

      - name: Copy the missing _sprite_share.scss file - related to GCWeb#1737 about wet-boew#cc340a6 commit
        run: |
          curl https://gist.githubusercontent.com/duboisp/d69787b300eb1f4d40f937508e10d013/raw/12cd8472baf6070d9868bdce3d961c3fb6320c83/_sprites_share.scss >> _sprites_share.scss
          mv _sprites_share.scss node_modules/wet-boew/src/plugins/share/sprites/_sprites_share.scss

      - name: Checkout wet-boew latest build
        run: |
          git clone --depth 1 https://github.com/wet-boew/wet-boew-cdn.git --branch v4.0-dist ~wet-boew-cdn
          mkdir -p node_modules/wet-boew/dist
          mv ~wet-boew-cdn/* node_modules/wet-boew/dist

      - name: Build GCWeb
        run: grunt dist

      - name: Git config
        run: |
          git config --global user.name "${{ secrets.my_username }}"
          git config --global user.email "${{ secrets.my_email }}"

      - name: Jekyll theme - Applying changes
        run: |
          git clone --depth 1 https://github.com/${{ secrets.repo_jekyll }}.git ~gcweb-jekyll
          rm -rf ~gcweb-jekyll/_includes
          rm -rf ~gcweb-jekyll/_layouts
          mv ~jekyll-dist/_includes ~gcweb-jekyll/_includes
          mv ~jekyll-dist/_layouts ~gcweb-jekyll/_layouts
          cd ~gcweb-jekyll
          git add .
          git commit -m "CD: Update GCWeb jekyll theme files" --allow-empty

      - name: Jekyll theme - Deploy
        uses: ad-m/github-push-action@master
        with:
          repository: ${{ secrets.repo_jekyll }}
          directory: ~gcweb-jekyll
          branch: master
          github_token: ${{ secrets.my_token }}


      - name: Compiled demos - Applying changes
        run: |
          git clone --depth 1 https://github.com/${{ secrets.repo_compiled_demos }}.git ~gcweb-compiled-demos
          rm -rf ~gcweb-compiled-demos/_wetboew-demos
          rm -rf ~gcweb-compiled-demos/méli-mélo-demos
          rm -rf ~gcweb-compiled-demos/_data/méli-mélo.json
          mv _wetboew-demos ~gcweb-compiled-demos/_wetboew-demos
          mv méli-mélo-demos ~gcweb-compiled-demos/méli-mélo-demos
          mkdir -p ~gcweb-compiled-demos/_data
          cp _data/méli-mélo.json ~gcweb-compiled-demos/_data/méli-mélo.json
          cd ~gcweb-compiled-demos
          git add .
          git commit -m "CD: Update GCWeb compiled demos files" --allow-empty

      - name: Compiled demos - Deploy
        uses: ad-m/github-push-action@master
        with:
          repository: ${{ secrets.repo_compiled_demos }}
          directory: ~gcweb-compiled-demos
          branch: master
          github_token: ${{ secrets.my_token }}


      - name: Dist - Applying changes
        run: |
          git clone --depth 1 https://github.com/${{ secrets.repo_dist }}.git --branch GCWeb ~gcweb-dist
          rm -rf ~gcweb-dist/wet-boew
          rm -rf ~gcweb-dist/GCWeb
          mv dist/wet-boew ~gcweb-dist/wet-boew
          mv dist/GCWeb ~gcweb-dist/GCWeb
          cp Licence-fr.txt ~gcweb-dist/GCWeb/Licence-fr.txt
          cp License-en.txt ~gcweb-dist/GCWeb/License-en.txt
          cd ~gcweb-dist
          git add .
          git commit -m "CD: Update GCWeb dist files" --allow-empty

      - name: Dist - Deploy in GCWeb branch
        uses: ad-m/github-push-action@master
        with:
          repository: ${{ secrets.repo_dist }}
          directory: ~gcweb-dist
          branch: GCWeb
          github_token: ${{ secrets.my_token }}

      - name: Dist CDN - Applying changes
        run: |
          git clone --depth 1 https://github.com/${{ secrets.repo_dist_cdn }}.git --branch GCWeb ~gcweb-cdn
          rm -rf ~gcweb-cdn/*
          cp -r ~gcweb-dist/GCWeb/. ~gcweb-cdn/
          cd ~gcweb-cdn
          git add .
          git commit -m "CD: Update GCWeb dist cdn files" --allow-empty

      - name: Dist CDN - Deploy in GCWeb branch
        uses: ad-m/github-push-action@master
        with:
          repository: ${{ secrets.repo_dist_cdn }}
          directory: ~gcweb-cdn
          branch: GCWeb
          github_token: ${{ secrets.my_token }}

#      - name: Dist - Update submodule
#        run: |
#          git clone --depth 1 https://github.com/${{ secrets.repo_dist }}.git --branch gh-pages ~gcweb-dist-submodule
#          cd ~gcweb-dist-submodule
#          git submodule update --single-branch --remote --init --depth 1 --branch GCWeb
#          git add .
#          git commit -m "CD: Update GCWeb dist files" --allow-empty
#
#      - name: Dist - Deploy submodule updated
#        uses: ad-m/github-push-action@master
#        with:
#          repository: ${{ secrets.repo_dist }}
#          directory: ~gcweb-dist-submodule
#          branch: gh-pages
#          github_token: ${{ secrets.my_token }}
