name: CD

on:
  push:

jobs:
  deploy-jekyll:

    runs-on: ubuntu-latest

    environment: continuous_deploy

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm i -g bower grunt-cli
          npm ci

      - name: Copy the missing _sprite_share.scss file - related to GCWeb#1737 about wet-boew#cc340a6 commit
        run: |
          curl https://gist.githubusercontent.com/duboisp/d69787b300eb1f4d40f937508e10d013/raw/12cd8472baf6070d9868bdce3d961c3fb6320c83/_sprites_share.scss >> _sprites_share.scss
          mv _sprites_share.scss node_modules/wet-boew/src/plugins/share/sprites/_sprites_share.scss

      - name: Build GCWeb
        run: grunt dist

      - name: Jekyll theme - Applying changes
        run: |
          git clone --depth 1 ${{ secrets.jekyll_repo }} ~gcweb-jekyll
          rm -r ~gcweb-jekyll/_includes
          rm -r ~gcweb-jekyll/_layouts
          mv ~jekyll-dist/_includes ~gcweb-jekyll/_includes
          mv ~jekyll-dist/_layouts ~gcweb-jekyll/_layouts

      - name: Jekyll theme - Preparing deployment
        run: |
          cd ~gcweb-jekyll
          git config --local user.name "${{ secrets.my_username }}"
          git config --local user.email "${{ secrets.my_email }}"
          git add .
          git commit -m "CD: Update GCWeb jekyll theme files" --allow-empty

      - name: Jekyll theme - Deploy
        uses: ad-m/github-push-action@master
        with:
          repository: duboisp/gcweb-jekyll
          directory: ~gcweb-jekyll
          branch: master
          github_token: ${{ secrets.my_token }}



