name: CI

on:
  pull_request:

jobs:
  integration-check:

    runs-on: ubuntu-latest

    environment: continuous_integration

    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2

      - name: Extract tag or branch name
        id: ref_name
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.my_token }}
          result-encoding: string
          # act use "\" and githbu use "/"
          script: |
            return context.ref.replace(/\/refs\/heads\//, '').replace(/\\refs\\heads\\/, '').replace(/\/refs\/tags\//, '').replace(/\\refs\\tags\\/, '')
      - name: Check if it a tag
        id: ref_tags
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.my_token }}
          # act use "\" and githbu use "/"
          script: |
            console.log( context.ref );
            return context.ref.startsWith("\\refs\\tags\\") || context.ref.startsWith("/refs\/tags\/") || ''
      - name: Tag or branch info
        env:
           ref_name: ${{ steps.ref_name.outputs.result }}
           is_tags: ${{ steps.ref_tags.outputs.result }}
        run: |
          echo Ref name: ${{ env.ref_name }}
          echo Is tag: ${{ env.is_tags }}

#      - name: Cache node modules
#        uses: actions/cache@v2
#        if: ${{ !env.ACT }}
#        env:
#          cache-name: cache-node-modules
#        with:
#          # npm cache files are stored in '~/.npm' on Linux/macOS
#          path: ~/.npm
#          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-build-${{ env.cache-name }}-
#            ${{ runner.os }}-build-
#            ${{ runner.os }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm i -g bower grunt-cli
          npm ci

      - name: Copy the missing _sprite_share.scss file - related to GCWeb#1737 about wet-boew#cc340a6 commit
        run: |
          curl https://gist.githubusercontent.com/duboisp/d69787b300eb1f4d40f937508e10d013/raw/12cd8472baf6070d9868bdce3d961c3fb6320c83/_sprites_share.scss >> _sprites_share.scss
          mv _sprites_share.scss node_modules/wet-boew/src/plugins/share/sprites/_sprites_share.scss

      - name: Checkout wet-boew latest build
        if: ${{ env.ACT }}
        run: |
          git clone --depth 1 https://github.com/wet-boew/wet-boew-cdn.git --branch v4.0-dist ~wet-boew-cdn
          mkdir -p node_modules/wet-boew/dist/wet-boew
          mv ~wet-boew-cdn/* node_modules/wet-boew/dist/wet-boew

      - name: Build GCWeb
        if: ${{ !env.ACT }}
        run: grunt dist

      - name: Build GCWeb (without pre-test)
        if: ${{ env.ACT }}
        run: grunt dist-act
