name: CI

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g bower grunt-cli
      - run: npm ci

      - name: npm install wet-boew dependency
        run: |
          cd node_modules/wet-boew
          npm i -g bower grunt-cli
          npm install
          grunt deploy-build

      - name: Build GCWeb
        if: ${{ !env.ACT }}
        run: grunt dist

      - name: Build GCWeb (without pre-test)
        if: ${{ env.ACT }}
        run: grunt dist-act
